services:
  - type: web
    name: careerlens-backend
    runtime: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
      - key: JWT
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://career-lens-weld.vercel.app
